Repository AlibudaLab/atomic-habit-builder, pull requests merged in 2024-09, with the labels that each got.

#185 fix: annoying navbar footer
  web/app/habit/components/NavbarFooter.tsx
  web/app/habit/create/components/createContent.tsx
  web/app/layout.tsx
  web/app/profile/components/ProfileContent.tsx
Labels: bug

#170 Add e2e testing
  web/cypress.config.ts
  web/cypress/e2e/openApp.cy.ts
  web/cypress/support/commands.ts
  web/cypress/support/e2e.ts
  web/package.json
  web/yarn.lock
Labels: cicd

#191 feat: easy deposit link
  web/app/habit/stake/components/AddFundPopup.tsx
  web/app/habit/stake/components/DepositPopup.tsx
  web/app/habit/stake/components/InsufficientBalancePopup.tsx
  web/app/habit/stake/components/stakeContent.tsx
  web/app/profile/components/ProfileContent.tsx
  web/src/constants.ts
  web/src/utils/bridge.ts
Labels: feature

#193 feat: trackers
  web/app/habit/checkin/components/activityDropdown.tsx
  web/app/habit/checkin/components/checkinRun.tsx
  web/app/habit/claim/components/claim.tsx
  web/app/habit/components/InviteLink.tsx
  web/app/habit/components/NavbarFooter.tsx
  web/app/habit/components/UserDashboard.tsx
  web/app/habit/create/components/createContent.tsx
  web/app/habit/create/components/step1.tsx
  web/app/habit/history/components/HistoryContent.tsx
  web/app/habit/list/components/challengeList.tsx
  web/app/habit/stake/components/DepositPopup.tsx
  web/app/habit/stake/components/stakeContent.tsx
  web/app/profile/components/ProfileContent.tsx
  web/src/hooks/transaction/useCheckInRun.ts
  web/src/hooks/transaction/useJoinChallenge.ts
  web/src/hooks/transaction/useTransferERC20.ts
  web/src/hooks/usePasskeyConnection.ts
  web/src/hooks/useSocialShare.ts
  web/src/utils/gtag.ts
Labels: feature

#201 hotfix: special page to handle withdraw funds
  web/app/Providers.tsx
  web/app/habit/stake/components/stakeContent.tsx
  web/app/withdraw/components/SpecialWithdraw.tsx
  web/app/withdraw/components/SpecialWithdrawPopup.tsx
  web/app/withdraw/page.tsx
  web/src/constants.ts
  web/src/hooks/transaction/useTransactionArbitraryChain.ts
  web/src/hooks/transaction/useTransferERC20ArbitraryChain.ts
  web/src/providers/PasskeyProvider.tsx
  web/src/providers/UserChallengesProvider.tsx
  web/src/store/createWagmiConfig.ts
Labels: bug, hotfix

#209 feat: invite code
  web/app/api/user/referral/exist/route.ts
  web/app/api/user/referral/invite/route.ts
  web/app/api/user/referral/route.ts
  web/app/connect-run/page.tsx
  web/app/connect-run/strava/page.tsx
  web/app/habit/checkin/components/ActivityCheckIn.tsx
  web/app/habit/components/InviteLink.tsx
  web/app/habit/components/Onboard.tsx
  web/app/layout.tsx
  web/app/profile/components/ProfileContent.tsx
  web/src/components/Connect/RegisterButton.tsx
  web/src/components/Connect/SignInAndRegister.tsx
  web/src/components/ReferralCodeHandler.tsx
  web/src/hooks/useChallengeWithCheckIns.ts
  web/src/hooks/useInviteLink.ts
  web/src/hooks/usePasskeyConnection.ts
  web/src/providers/PasskeyProvider.tsx
  web/src/utils/referralCode.ts
  web/src/utils/referralStorage.ts
Labels: feature
